### ISSUE TITLE
ApiPort roadmap

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#911]
We use this issue to track the new features and improvement plan. The work items on the list are identified and prioritized by customer feedbacks. If you like to propose new items to be addd or increase the priority of the existing item, please open issue or vote on existing issue.

- [ ] Improve recommended changes for missing APIs https://github.com/microsoft/dotnet-apiport/issues/773
- [ ] Improve migration documentations for not supported technical areas in .NET Core https://github.com/microsoft/dotnet-apiport/issues/912
- [x] Report .NET Core APIs throwing PlatformNotsupportedException and NotImplementedException https://github.com/microsoft/dotnet-apiport/pull/897
- [x] Suggest components porting order based on entrypoint assembly https://github.com/microsoft/dotnet-apiport/pull/906
- [ ] Show the absolute count of missing APIs instead of percentages on the summary page to make the summary page more useful https://github.com/microsoft/dotnet-apiport/issues/913
- [ ] Identify commonly used nuget packages that are used and provide links to portable version if available  https://github.com/microsoft/dotnet-apiport/issues/892  
- [ ] Report number of calls to missing .NET APIs to help estimate porting cost https://github.com/microsoft/dotnet-apiport/issues/858

**Comment by Lxiamail** [comment]
#897 #906

**Comment by mjrousos** [comment]
One thing that I've seen experienced users do with ApiPort that would be great to somehow captured for people newer to the tool is to quickly scan missing NetFx APIs to look for 'red flag' APIs that may make porting more difficult. 

For example, if I see WebForms or WCF server APIs in a customer's report, I know they have a more difficult port ahead compared to a different customer that is only missing APIs with easy replacements (even if that second report is missing a larger number of APIs).

Could we expand #913 to also give some sense of whether the missing APIs are 'easy' or 'hard' to replace? @twsouthwick and I along with the product teams could probably help to bucketize APIs in the catalog for this purpose. I think that sort of view would be the most useful summary page (count of APIs is better than %, but still could be misleading).

**Comment by Lxiamail** [comment]
@mjrousos Thanks for your suggestion. It makes sense. I will definitly leverage yours and @twsouthwick's help to bucketize the APIs.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
